#!/usr/bin/env python3
from os import setuid, setgid, execvp, environ, mkdir, chmod, chown, chdir, walk, stat
from os.path import ismount, isdir, join, exists
from pwd import getpwuid
from grp import getgrgid
from argparse import ArgumentParser
from subprocess import call

def main():
    parser = ArgumentParser("simlog", description="Simulate a 'real' user login process")
    parser.add_argument("--uid", required=True, type=int)
    parser.add_argument("--gid", required=True, type=int)
    parser.add_argument("program", nargs="*")
    args = parser.parse_args()
    pwd = getpwuid(args.uid)
    grp = getgrgid(args.gid)
    print(f"Uid is {args.uid} ({pwd.pw_name}, {pwd.pw_dir})")
    print(f"Gid is {args.gid} ({grp.gr_name})")

    print(f"Setting $USER to {pwd.pw_name}")
    environ["USER"] = pwd.pw_name

    print(f"Setting $HOME to {pwd.pw_dir}")
    environ["HOME"] = pwd.pw_dir

    print(f"Preparing XDG_RUNTIME_DIR")
    runtime_dir_path = join("/run", "user", str(args.uid))
    if(not isdir(runtime_dir_path)):
        print(f"Path {runtime_dir_path} does not exists, creating")
        mkdir(runtime_dir_path)
        chmod(runtime_dir_path, 0o700)
        chown(runtime_dir_path, args.uid, args.gid)
    else:
        print("Path already exists, skipping")
    if(not ismount(runtime_dir_path)):
        print(f"Path {runtime_dir_path} has no tmpfs mounted, doing so")
        ret = call(["mount", "-t", "tmpfs", "-o", f"mode=700,uid={args.uid},gid={args.gid}", "tmpfs", runtime_dir_path])
        if(ret != 0):
            raise Exception("Unable to create tmpfs")
    else:
        print("tmpfs is already mounted, skipping")
    print(f"Setting $XDG_RUNTIME_DIR to {runtime_dir_path}")
    environ["XDG_RUNTIME_DIR"] = runtime_dir_path

    print(f"Swapping over gid to {args.gid}")
    setgid(args.gid)

    print(f"Swapping over uid to {args.uid}")
    setuid(args.uid)

    print(f"Starting session dbus")
    dbus_path = join(runtime_dir_path, "bus")
    if(not exists(dbus_path)):
        dbus_address = f"unix:path={dbus_path}"
        print(f"D-bus path is {dbus_path}")
        print(f"D-bus address is {dbus_address}")
        ret = call(["dbus-daemon", "--session", "--address", dbus_address, "--fork"])
        if(ret != 0):
            raise Exception("Unable to start session dbus")
    else:
        print("D-bus already running, skipping")

    print(f"Adjusting permissions in $XDG_RUNTIME_DIR")
    for root, dirs, files in walk(runtime_dir_path):
        for directoryPath in (join(root, dir) for dir in dirs):
            current_uid = stat(directoryPath).st_uid
            if(current_uid != args.uid):
                print(f"Fixing {directoryPath}: {current_uid} --> {args.uid}")
                chown(directoryPath, args.uid)
        for filePath in (join(root, file) for file in files):
            current_uid = stat(filePath).st_uid
            if(current_uid != args.uid):
                print(f"Fixing {filePath}: {current_uid} --> {args.uid}")
                chown(filePath, args.uid)
    print("Adjustment completed")

    print(f"Pivoting pwd to $HOME")
    chdir(pwd.pw_dir)

    print(f"Replacing process with {args.program}")
    execvp(args.program[0], [args.program[0], *args.program[1:]])

if __name__ == "__main__":
    main()